### ISSUE TITLE
defensewebtech

### ISSUE THREAD

**Issue by defensewebtech** [illust-bio/illust.bio#2]
# New Subdomain

Subdomain requested: `defensewebtechillust.bio`

Use this section to describe how will use this subdomain. Also provide links to your all your SNS where you post things related to the subdomain's purpose. If you wish to (and find it useful), you can describe yourself in a sentence or two so that we can see what you do (this will help us verify your request faster).

## Records

Add all the initial records that you want to create to this table. `@` means your subdomain (not the tld). All record names that are not `@` will be added to `defensewebtech.somrat.illust.bio`.

| Type | Name | Content | CF Proxy | TTL |
|------|------|---------|----------|-----|

## Tasks

Mark these filling the [ ] with an x when they're done.

- [x] I've specified everything I'm going to do with this subdomain
- [x] I've provided enough details to verify that I'm acceptable for the subdomain
- [x] I've added all the records I want to add to this subdomain (you can modify these later).
- [x] I've read and accepted the [Terms of Use](https//github.com/Nekidev/illust.bio/blob/main/TERMS.md)
